export const routes = [
  {
    path: "/showcase",
    layout: "auth",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"tangan"},
    component: () => import('./../pages/showcase/ShowcasePage.vue'),
  },
  {
    path: "/login",
    layout: "auth",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/login/LoginPage.vue'),
  },
  {
    path: "/assets",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/assets/AssetsPage.vue'),
  },
  {
    path: "/assets/avatars",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/assets/avatars/AssetsAvatarsPage.vue'),
  },
  {
    path: "/assets/products",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/assets/products/AssetsProductsPage.vue'),
  },
  {
    path: "/assets/resources",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/assets/resources/AssetsResourcesPage.vue'),
  },
  {
    path: "/assets/shops",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/assets/shops/AssetsShopsPage.vue'),
  },
  {
    path: "/agent",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/agent/AgentPage.vue'),
  },
  {
    path: "/chat",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/chat/ChatPage.vue'),
  },
  {
    path: "/create",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/CreatePage.vue'),
  },
  {
    path: "/create/angles",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/angles/CreateAnglesPage.vue'),
  },
  {
    path: "/create/formulas",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/formulas/CreateFormulasPage.vue'),
  },
  {
    path: "/create/hooks",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/hooks/CreateHooksPage.vue'),
  },
  {
    path: "/create/hooks3e60",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/hooks3e60/CreateHooks3e60Page.vue'),
  },
  {
    path: "/create/hottest-videos",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/hottest-videos/CreateHottestVideosPage.vue'),
  },
  {
    path: "/create/image",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/image/CreateImagePage.vue'),
  },
  {
    path: "/create/money-shots",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/money-shots/CreateMoneyShotsPage.vue'),
  },
  {
    path: "/create/my-creations",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/my-creations/CreateMyCreationsPage.vue'),
  },
  {
    path: "/create/script-generator",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/script-generator/CreateScriptGeneratorPage.vue'),
  },
  {
    path: "/create/video-analysis",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/video-analysis/CreateVideoAnalysisPage.vue'),
  },
  {
    path: "/create/video",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/create/video/CreateVideoPage.vue'),
  },
  {
    path: "/discover",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/DiscoverPage.vue'),
  },
  {
    path: "/discover/overview",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/overview/DiscoverOverviewPage.vue'),
  },
  {
    path: "/discover/overview/markets",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/overview/markets/DiscoverOverviewMarketsPage.vue'),
  },
  {
    path: "/discover/overview/opportunities",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/overview/opportunities/DiscoverOverviewOpportunitiesPage.vue'),
  },
  {
    path: "/discover/overview/pulse",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/overview/pulse/DiscoverOverviewPulsePage.vue'),
  },
  {
    path: "/discover/shopify/ads",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/shopify/ads/DiscoverShopifyAdsPage.vue'),
  },
  {
    path: "/discover/shopify/products",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/shopify/products/DiscoverShopifyProductsPage.vue'),
  },
  {
    path: "/discover/shopify/shops",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/shopify/shops/DiscoverShopifyShopsPage.vue'),
  },
  {
    path: "/discover/tiktok/ads",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/ads/DiscoverTiktokAdsPage.vue'),
  },
  {
    path: "/discover/tiktok/creators",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/creators/DiscoverTiktokCreatorsPage.vue'),
  },
  {
    path: "/discover/tiktok/creators/agency",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/creators/agency/DiscoverTiktokCreatorsAgencyPage.vue'),
  },
  {
    path: "/discover/tiktok/creators/commercial",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/creators/commercial/DiscoverTiktokCreatorsCommercialPage.vue'),
  },
  {
    path: "/discover/tiktok/creators/growth",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/creators/growth/DiscoverTiktokCreatorsGrowthPage.vue'),
  },
  {
    path: "/discover/tiktok/lives",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/lives/DiscoverTiktokLivesPage.vue'),
  },
  {
    path: "/discover/tiktok/products",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/products/DiscoverTiktokProductsPage.vue'),
  },
  {
    path: "/discover/tiktok/products/most-promoted",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/products/most-promoted/DiscoverTiktokProductsMostPromotedPage.vue'),
  },
  {
    path: "/discover/tiktok/products/new-arrivals",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/products/new-arrivals/DiscoverTiktokProductsNewArrivalsPage.vue'),
  },
  {
    path: "/discover/tiktok/products/top-selling",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/products/top-selling/DiscoverTiktokProductsTopSellingPage.vue'),
  },
  {
    path: "/discover/tiktok/shops",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/shops/DiscoverTiktokShopsPage.vue'),
  },
  {
    path: "/discover/tiktok/shops/most-promoted",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/shops/most-promoted/DiscoverTiktokShopsMostPromotedPage.vue'),
  },
  {
    path: "/discover/tiktok/shops/top-selling",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/shops/top-selling/DiscoverTiktokShopsTopSellingPage.vue'),
  },
  {
    path: "/discover/tiktok/videos",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/videos/DiscoverTiktokVideosPage.vue'),
  },
  {
    path: "/discover/tiktok/videos/b2b",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/tiktok/videos/b2b/DiscoverTiktokVideosB2bPage.vue'),
  },
  {
    path: "/discover/watchlist",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/discover/watchlist/DiscoverWatchlistPage.vue'),
  },
  {
    path: "/social",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/social/SocialPage.vue'),
  },
  {
    path: "/social/accounts",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/social/accounts/SocialAccountsPage.vue'),
  },
  {
    path: "/social/analytics",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/social/analytics/SocialAnalyticsPage.vue'),
  },
  {
    path: "/social/calendar",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/social/calendar/SocialCalendarPage.vue'),
  },
  {
    path: "/social/comments",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/social/comments/SocialCommentsPage.vue'),
  },
  {
    path: "/social/messages",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/social/messages/SocialMessagesPage.vue'),
  },
  {
    path: "/social/posts",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/social/posts/SocialPostsPage.vue'),
  },
  {
    path: "/social/posts/batch-publish",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/social/posts/batch-publish/SocialPostsBatchPublishPage.vue'),
  },
  {
    path: "/tasks",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/tasks/TasksPage.vue'),
  },
  {
    path: "/workspace",
    bodyClass: "geist_45906e97-module__4TOE8G__variable geist_mono_ecbcca75-module__nHvC6W__variable newsreader_2fc8840f-module__pEW9eG__variable playfair_display_ae79c37e-module__P7JKOq__variable antialiased",
    htmlAttrs: {"lang":"zh","dataBrand":"chj"},
    component: () => import('./../pages/workspace/WorkspacePage.vue'),
  },
]

export const routeFallback = '/login'
